//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdplForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RahmanDbEntities : DbContext
    {
        public RahmanDbEntities()
            : base("name=RahmanDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblOrderDt> tblOrderDts { get; set; }
        public virtual DbSet<tblOrderMst> tblOrderMsts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductDetail> tblProductDetails { get; set; }
        public virtual DbSet<CustOrderDetail> CustOrderDetails { get; set; }
        public virtual DbSet<tblCustDetail> tblCustDetails { get; set; }
    }
}
